services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-faq_db}
      POSTGRES_USER: ${POSTGRES_USER:-faq_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-faq_password}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  postgres_data: